title: DentaVacation
description: "Explore DentaVacation's allure through captivating app screenshots"

# author:
#   name: Yashas H Majmudar
#   email: yashashm.dev@gmail.com

google_analytics:
theme: jekyll-theme-minimal
# color-scheme: ["auto-default-dark"]
