title: DentaVacation
description: "Explore DentaVacation's allure through captivating app screenshots"

# author:
#   name: Yashas H Majmudar
#   email: yashashm.dev@gmail.com

google_analytics:


remote-theme: "dracula/gh-pages"
show_header: false
colorspace: cyan
# color-scheme: ["auto-default-dark"]
