title: DentaVacation
description: "Explore DentaVacation's allure through captivating app screenshots"

# author:
#   name: Yashas H Majmudar
#   email: yashashm.dev@gmail.com

google_analytics:
show_downloads: false

remote-theme: "godalming123/minimal"
color-scheme: "dark"
