title: DentaVacation
description: "Explore DentaVacation's allure through captivating app screenshots"
author:
  name: Yashas H Majmudar
  email: yashashm.dev@gmail.com

google_analytics:
show_downloads: false

remote_theme: jekyll/minima

minima:
  skin: "dark"
