title: DentaVacation
description: "Explore DentaVacation's allure through captivating app screenshots"

# author:
#   name: Yashas H Majmudar
#   email: yashashm.dev@gmail.com
remote-theme: dracula/gh-pages
google_analytics:
show_header: false
colorspace: cyan
# color-scheme: ["auto-default-dark"]
